repos:
- hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
  - id: trailing-whitespace
  - id: check-case-conflict
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 21.5b1
- hooks:
  - id: skjold
  repo: https://github.com/twu/skjold
  rev: v0.4.1
- hooks:
  - id: mypy
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
- hooks:
  - id: flake8
  repo: https://github.com/pycqa/flake8
  rev: 4.0.1
- hooks:
  - id: commitizen
    stages:
      - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.20.0
